function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(41)=1;
    ys_(42)=1;
    ys_(43)=1;
    ys_(34)=1;
    ys_(40)=1;
    ys_(33)=1;
    ys_(35)=ys_(34)*ys_(33);
    MU=params(4)/(params(4)-1);
    [ys_(32),ys_(25),ys_(38),ys_(28),ys_(29),ys_(7),ys_(8),ys_(9),ys_(13),ys_(14),ys_(15),ys_(1),ys_(2),ys_(3),ys_(4),ys_(5),ys_(6),ys_(31),ys_(26),ys_(27)]=soe_ss_solve(params(8),params(9),params(10),params(11),params(12),params(13),params(14),params(15),params(16),params(17),params(18),params(20),params(21),params(23),params(24),params(2),params(3),MU);
    ys_(39)=ys_(38)*ys_(28)/ys_(35);
    ys_(10)=1;
    ys_(11)=1;
    ys_(12)=1;
    ys_(30)=1;
    ys_(16)=1;
    ys_(17)=1;
    ys_(18)=1;
    ys_(19)=ys_(1)*ys_(13)/ys_(7)/(1-(1-params(5))*params(1));
    ys_(20)=ys_(1)/(1-(1-params(5))*params(1));
    ys_(21)=ys_(2)*ys_(14)/ys_(8)/(1-params(1)*(1-params(6)));
    ys_(22)=ys_(2)/(1-params(1)*(1-params(6)));
    ys_(23)=ys_(3)*ys_(15)/ys_(9)/(1-params(1)*(1-params(7)));
    ys_(24)=ys_(3)/(1-params(1)*(1-params(7)));
    ys_(37)=1/params(1);
    ys_(36)=params(25);
    ys_(44)=0;
    ys_(45)=0;
    ys_(46)=0;
    ys_(47)=0;
    ys_(48)=0;
    ys_(49)=ys_(38)*ys_(28)+ys_(25)*ys_(29)-ys_(35)*ys_(39);
    % Auxiliary equations
end
