// =========================================================================
// Open-Economy Production-Network New Keynesian Model
// Rubbo (2024) extended to a Small Open Economy -- FULL-NATIVE-RESOLUTION
// CHILE DATA CALIBRATION, N=12 sectors
//
// AUTO-GENERATED by data_calibration/generate_mod.py from
// chile_calibration_full_results.json -- do not hand-edit; edit the
// calibration script or generator and regenerate instead.
//
// Source: Banco Central de Chile, Cuadros 12x12, ano base 2008 (precios basicos) (FULL 12-activity resolution, no 3-sector aggregation)
//
// Full-resolution generalization of open_economy_network_chile.mod (which
// hand-derives (I-Omega^H)^-1 via a 3x3 cofactor formula written as scalar
// Dynare parameter algebra -- infeasible at N=12). Instead:
//   - LAMBDA_D_i (Domar/domestic-supplier centrality) and WDC_i (DC-index
//     weights) are computed in Python (numpy.linalg.inv) and written in here
//     as plain calibrated CONSTANTS, not derived via in-Dynare matrix
//     inversion -- see data_calibration/full_calibration_common.py.
//   - The steady state is solved by soe_ss_solve_dense_N.m /
//     soe_ss_resid_dense_N.m, ordinary MATLAB matrix algebra (backslash
//     solves), generalizing soe_ss_solve_dense.m/soe_ss_resid_dense.m from
//     3x3 to NxN.
//   - DELTA_i (raw Calvo reset probability) is NOT identifiable from IO data
//     at any resolution; each raw sector inherits its macro-category's
//     (Resource/Manufacturing/Services) literature default (Dhyne et al.
//     2005/ECB IPN), via a category concordance kept ONLY for this purpose
//     -- see build_chile_calibration.py's build_full().
//
// REGIMES (set via -DREGIME=... on the command line):
//   float    Taylor rule targets the DC index (benchmark)
//   peg      exchange rate fixed, S_t = 1
//   managed  Taylor rule + partial FX stabilisation
//   cpi_it   strict CPI (PIC) inflation targeting
//   ppi_it   strict PPI/domestic-bundle (PH) inflation targeting
// =========================================================================

@#ifndef REGIME
@#define REGIME = "managed"
@#endif

// -------------------------------------------------------------------------
// VARIABLES
// -------------------------------------------------------------------------
var
  Y1 L1 P1 PI1 MC1 PSTAR1 X1_1 X2_1 A1 y_gap1
  Y2 L2 P2 PI2 MC2 PSTAR2 X1_2 X2_2 A2 y_gap2
  Y3 L3 P3 PI3 MC3 PSTAR3 X1_3 X2_3 A3 y_gap3
  Y4 L4 P4 PI4 MC4 PSTAR4 X1_4 X2_4 A4 y_gap4
  Y5 L5 P5 PI5 MC5 PSTAR5 X1_5 X2_5 A5 y_gap5
  Y6 L6 P6 PI6 MC6 PSTAR6 X1_6 X2_6 A6 y_gap6
  Y7 L7 P7 PI7 MC7 PSTAR7 X1_7 X2_7 A7 y_gap7
  Y8 L8 P8 PI8 MC8 PSTAR8 X1_8 X2_8 A8 y_gap8
  Y9 L9 P9 PI9 MC9 PSTAR9 X1_9 X2_9 A9 y_gap9
  Y10 L10 P10 PI10 MC10 PSTAR10 X1_10 X2_10 A10 y_gap10
  Y11 L11 P11 PI11 MC11 PSTAR11 X1_11 X2_11 A11 y_gap11
  Y12 L12 P12 PI12 MC12 PSTAR12 X1_12 X2_12 A12 y_gap12
  C CH CF PH PC PIC Ltot W S PF PFH BSTAR I EX IM DSTAR PX RP piDC y_gap GDP
;

// -------------------------------------------------------------------------
// EXOGENOUS SHOCKS
// -------------------------------------------------------------------------
varexo eps_a1 eps_a2 eps_a3 eps_a4 eps_a5 eps_a6 eps_a7 eps_a8 eps_a9 eps_a10 eps_a11 eps_a12 eps_pF eps_D eps_pX eps_rp;

// -------------------------------------------------------------------------
// PARAMETERS
// -------------------------------------------------------------------------
parameters
  ALPHA1 OF1 BH1 DELTA1 DHAT1 LAMBDA_D1 WDC1
  ALPHA2 OF2 BH2 DELTA2 DHAT2 LAMBDA_D2 WDC2
  ALPHA3 OF3 BH3 DELTA3 DHAT3 LAMBDA_D3 WDC3
  ALPHA4 OF4 BH4 DELTA4 DHAT4 LAMBDA_D4 WDC4
  ALPHA5 OF5 BH5 DELTA5 DHAT5 LAMBDA_D5 WDC5
  ALPHA6 OF6 BH6 DELTA6 DHAT6 LAMBDA_D6 WDC6
  ALPHA7 OF7 BH7 DELTA7 DHAT7 LAMBDA_D7 WDC7
  ALPHA8 OF8 BH8 DELTA8 DHAT8 LAMBDA_D8 WDC8
  ALPHA9 OF9 BH9 DELTA9 DHAT9 LAMBDA_D9 WDC9
  ALPHA10 OF10 BH10 DELTA10 DHAT10 LAMBDA_D10 WDC10
  ALPHA11 OF11 BH11 DELTA11 DHAT11 LAMBDA_D11 WDC11
  ALPHA12 OF12 BH12 DELTA12 DHAT12 LAMBDA_D12 WDC12
  OH1_1 OH1_2 OH1_3 OH1_4 OH1_5 OH1_6 OH1_7 OH1_8 OH1_9 OH1_10 OH1_11 OH1_12
  OH2_1 OH2_2 OH2_3 OH2_4 OH2_5 OH2_6 OH2_7 OH2_8 OH2_9 OH2_10 OH2_11 OH2_12
  OH3_1 OH3_2 OH3_3 OH3_4 OH3_5 OH3_6 OH3_7 OH3_8 OH3_9 OH3_10 OH3_11 OH3_12
  OH4_1 OH4_2 OH4_3 OH4_4 OH4_5 OH4_6 OH4_7 OH4_8 OH4_9 OH4_10 OH4_11 OH4_12
  OH5_1 OH5_2 OH5_3 OH5_4 OH5_5 OH5_6 OH5_7 OH5_8 OH5_9 OH5_10 OH5_11 OH5_12
  OH6_1 OH6_2 OH6_3 OH6_4 OH6_5 OH6_6 OH6_7 OH6_8 OH6_9 OH6_10 OH6_11 OH6_12
  OH7_1 OH7_2 OH7_3 OH7_4 OH7_5 OH7_6 OH7_7 OH7_8 OH7_9 OH7_10 OH7_11 OH7_12
  OH8_1 OH8_2 OH8_3 OH8_4 OH8_5 OH8_6 OH8_7 OH8_8 OH8_9 OH8_10 OH8_11 OH8_12
  OH9_1 OH9_2 OH9_3 OH9_4 OH9_5 OH9_6 OH9_7 OH9_8 OH9_9 OH9_10 OH9_11 OH9_12
  OH10_1 OH10_2 OH10_3 OH10_4 OH10_5 OH10_6 OH10_7 OH10_8 OH10_9 OH10_10 OH10_11 OH10_12
  OH11_1 OH11_2 OH11_3 OH11_4 OH11_5 OH11_6 OH11_7 OH11_8 OH11_9 OH11_10 OH11_11 OH11_12
  OH12_1 OH12_2 OH12_3 OH12_4 OH12_5 OH12_6 OH12_7 OH12_8 OH12_9 OH12_10 OH12_11 OH12_12
  BETA GAMMA VARPHI EPS BF_TOT OMEGA ETA PSI THETA_S KAPEX_SCALE BSTARBAR ISTAR PHI_PI PHI_Y PHI_S RHO_A RHO_PF RHO_D RHO_PX RHO_RP
;

// -------------------------------------------------------------------------
// PARAMETER VALUES (primitive calibration)
// -------------------------------------------------------------------------
BETA = 0.99;
GAMMA = 1.0;
VARPHI = 2.0;
EPS = 8.0;
// Raw Calvo reset probabilities: literature default by macro-category
// (Resource/Manufacturing/Services -- Dhyne et al. 2005/ECB IPN, see
// open_economy_network_chile.mod's DELTA1-3 comment for full derivation),
// assigned per RAW sector via the category concordance kept in the
// calibration script SOLELY for this purpose (all other objects below are
// genuine full-resolution IO data, not category aggregates).
DELTA1 = 0.900000;
DELTA2 = 0.900000;
DELTA3 = 0.900000;
DELTA4 = 0.310000;
DELTA5 = 0.310000;
DELTA6 = 0.310000;
DELTA7 = 0.160000;
DELTA8 = 0.160000;
DELTA9 = 0.160000;
DELTA10 = 0.160000;
DELTA11 = 0.160000;
DELTA12 = 0.160000;
// Value-added shares (ALPHA), domestic IO matrix (OH), import cost shares
// (OF), household consumption shares (BH): DATA, full native resolution.
ALPHA1 = 0.40213948;
ALPHA2 = 0.21672929;
ALPHA3 = 0.59329898;
ALPHA4 = 0.25703556;
ALPHA5 = 0.26769304;
ALPHA6 = 0.46799711;
ALPHA7 = 0.45847278;
ALPHA8 = 0.35542761;
ALPHA9 = 0.66135834;
ALPHA10 = 0.78231363;
ALPHA11 = 0.71411840;
ALPHA12 = 0.70096507;
OH1_1 = 0.06320932;
OH1_2 = 0.00000000;
OH1_3 = 0.00476392;
OH1_4 = 0.14250602;
OH1_5 = 0.01265491;
OH1_6 = 0.00170495;
OH1_7 = 0.06282733;
OH1_8 = 0.02032821;
OH1_9 = 0.15575637;
OH1_10 = 0.00000000;
OH1_11 = 0.00266682;
OH1_12 = 0.00020474;
OH2_1 = 0.00012092;
OH2_2 = 0.12346705;
OH2_3 = 0.00004741;
OH2_4 = 0.43570390;
OH2_5 = 0.00577800;
OH2_6 = 0.00279020;
OH2_7 = 0.05696870;
OH2_8 = 0.03913881;
OH2_9 = 0.05447236;
OH2_10 = 0.00000000;
OH2_11 = 0.00525472;
OH2_12 = 0.00000000;
OH3_1 = 0.00000000;
OH3_2 = 0.00000000;
OH3_3 = 0.09543790;
OH3_4 = 0.07121984;
OH3_5 = 0.05938844;
OH3_6 = 0.00085600;
OH3_7 = 0.01714699;
OH3_8 = 0.02108108;
OH3_9 = 0.06818648;
OH3_10 = 0.00000000;
OH3_11 = 0.00145292;
OH3_12 = 0.00000000;
OH4_1 = 0.07973158;
OH4_2 = 0.04590470;
OH4_3 = 0.03419616;
OH4_4 = 0.13682964;
OH4_5 = 0.02788128;
OH4_6 = 0.00162233;
OH4_7 = 0.03674996;
OH4_8 = 0.03593973;
OH4_9 = 0.08370050;
OH4_10 = 0.00000000;
OH4_11 = 0.00130983;
OH4_12 = 0.00000000;
OH5_1 = 0.00000000;
OH5_2 = 0.00000000;
OH5_3 = 0.00113152;
OH5_4 = 0.07365742;
OH5_5 = 0.41612577;
OH5_6 = 0.00871830;
OH5_7 = 0.01150140;
OH5_8 = 0.01926977;
OH5_9 = 0.02532722;
OH5_10 = 0.00000000;
OH5_11 = 0.00224733;
OH5_12 = 0.00000000;
OH6_1 = 0.00023445;
OH6_2 = 0.00000000;
OH6_3 = 0.00572188;
OH6_4 = 0.23361704;
OH6_5 = 0.00448296;
OH6_6 = 0.00069805;
OH6_7 = 0.06565441;
OH6_8 = 0.01082806;
OH6_9 = 0.10821143;
OH6_10 = 0.00000000;
OH6_11 = 0.00066430;
OH6_12 = 0.00000000;
OH7_1 = 0.00458941;
OH7_2 = 0.00033722;
OH7_3 = 0.00004063;
OH7_4 = 0.08266429;
OH7_5 = 0.01893675;
OH7_6 = 0.00832489;
OH7_7 = 0.05784512;
OH7_8 = 0.10625043;
OH7_9 = 0.21424646;
OH7_10 = 0.00000000;
OH7_11 = 0.00262707;
OH7_12 = 0.00125495;
OH8_1 = 0.00000001;
OH8_2 = 0.00000000;
OH8_3 = 0.00000000;
OH8_4 = 0.06437846;
OH8_5 = 0.00980396;
OH8_6 = 0.00593295;
OH8_7 = 0.04754713;
OH8_8 = 0.15909685;
OH8_9 = 0.11216299;
OH8_10 = 0.00000000;
OH8_11 = 0.00114313;
OH8_12 = 0.00043808;
OH9_1 = 0.00058016;
OH9_2 = 0.00000000;
OH9_3 = 0.00020489;
OH9_4 = 0.02536149;
OH9_5 = 0.00842521;
OH9_6 = 0.00514902;
OH9_7 = 0.01729911;
OH9_8 = 0.02447602;
OH9_9 = 0.20651793;
OH9_10 = 0.00000000;
OH9_11 = 0.00263974;
OH9_12 = 0.00000000;
OH10_1 = 0.00000000;
OH10_2 = 0.00000000;
OH10_3 = 0.00000000;
OH10_4 = 0.00000000;
OH10_5 = 0.00000000;
OH10_6 = 0.16955740;
OH10_7 = 0.00000000;
OH10_8 = 0.00000000;
OH10_9 = 0.04812897;
OH10_10 = 0.00000000;
OH10_11 = 0.00000000;
OH10_12 = 0.00000000;
OH11_1 = 0.00127657;
OH11_2 = 0.00001162;
OH11_3 = 0.00000000;
OH11_4 = 0.05051874;
OH11_5 = 0.02261469;
OH11_6 = 0.00910584;
OH11_7 = 0.03187704;
OH11_8 = 0.01412617;
OH11_9 = 0.09410135;
OH11_10 = 0.00000000;
OH11_11 = 0.03890987;
OH11_12 = 0.00006164;
OH12_1 = 0.00224702;
OH12_2 = 0.00000000;
OH12_3 = 0.00000000;
OH12_4 = 0.03147818;
OH12_5 = 0.02916905;
OH12_6 = 0.03343283;
OH12_7 = 0.01455027;
OH12_8 = 0.03234768;
OH12_9 = 0.07596140;
OH12_10 = 0.00000000;
OH12_11 = 0.01834839;
OH12_12 = 0.00000000;
OF1 = 0.13123792;
OF2 = 0.05952864;
OF3 = 0.07193137;
OF4 = 0.25909873;
OF5 = 0.17432823;
OF6 = 0.10189032;
OF7 = 0.04440999;
OF8 = 0.24406883;
OF9 = 0.04798809;
OF10 = 0.00000000;
OF11 = 0.02327807;
OF12 = 0.06150009;
BH1 = 0.01888982;
BH2 = 0.00136508;
BH3 = 0.00000946;
BH4 = 0.21083581;
BH5 = 0.03868292;
BH6 = 0.00000000;
BH7 = 0.21137910;
BH8 = 0.12173052;
BH9 = 0.11205777;
BH10 = 0.13235207;
BH11 = 0.15157195;
BH12 = 0.00112549;
BF_TOT = 0.1;
OMEGA = 1 - BF_TOT;
ETA = 1.5;
PSI = 0.02;
THETA_S = 2.0;
KAPEX_SCALE = 0.5;
BSTARBAR = 0.0;
PHI_PI = 1.5;
PHI_Y = 0.5;
PHI_S = 0.3;
RHO_A = 0.9;
RHO_PF = 0.85;
RHO_D = 0.8;
RHO_PX = 0.85;
RHO_RP = 0.8;
ISTAR = 1/BETA;

// -------------------------------------------------------------------------
// DERIVED NETWORK / POLICY OBJECTS
// (computed in Python from the calibrated OmegaH/OmegaF/betaH/DELTA -- see
// data_calibration/full_calibration_common.py -- and inserted here as plain
// calibrated constants, per the "avoid hand-unrolling matrix algebra in
// Dynare" architectural decision for N>3.)
// -------------------------------------------------------------------------
DHAT1 = 0.8902184653;
DHAT2 = 0.8902184653;
DHAT3 = 0.8902184653;
DHAT4 = 0.1246309812;
DHAT5 = 0.1246309812;
DHAT6 = 0.1246309812;
DHAT7 = 0.0310792854;
DHAT8 = 0.0310792854;
DHAT9 = 0.0310792854;
DHAT10 = 0.0310792854;
DHAT11 = 0.0310792854;
DHAT12 = 0.0310792854;
LAMBDA_D1 = 0.0510006893;
LAMBDA_D2 = 0.0195607617;
LAMBDA_D3 = 0.0136168783;
LAMBDA_D4 = 0.3417580491;
LAMBDA_D5 = 0.1087458837;
LAMBDA_D6 = 0.0308000819;
LAMBDA_D7 = 0.2680973522;
LAMBDA_D8 = 0.2108901809;
LAMBDA_D9 = 0.3268958954;
LAMBDA_D10 = 0.1323520695;
LAMBDA_D11 = 0.1606303313;
LAMBDA_D12 = 0.0015746732;
WDC1 = 0.0001668363;
WDC2 = 0.0000639883;
WDC3 = 0.0000445443;
WDC4 = 0.0636745220;
WDC5 = 0.0202609483;
WDC6 = 0.0057385056;
WDC7 = 0.2217131871;
WDC8 = 0.1744035655;
WDC9 = 0.2703388535;
WDC10 = 0.1094535209;
WDC11 = 0.1328392929;
WDC12 = 0.0013022353;

// -------------------------------------------------------------------------
// MODEL BLOCK (nonlinear -- levels, NOT model(linear))
// -------------------------------------------------------------------------
model;

//------------------------------------------------------------
// [1] Nominal marginal cost, Cobb-Douglas cost minimization (dense N x N)
//------------------------------------------------------------
MC1 = (1/A1) * W^ALPHA1 * P1^OH1_1 * P2^OH1_2 * P3^OH1_3 * P4^OH1_4 * P5^OH1_5 * P6^OH1_6 * P7^OH1_7 * P8^OH1_8 * P9^OH1_9 * P10^OH1_10 * P11^OH1_11 * P12^OH1_12 * PFH^OF1;
MC2 = (1/A2) * W^ALPHA2 * P1^OH2_1 * P2^OH2_2 * P3^OH2_3 * P4^OH2_4 * P5^OH2_5 * P6^OH2_6 * P7^OH2_7 * P8^OH2_8 * P9^OH2_9 * P10^OH2_10 * P11^OH2_11 * P12^OH2_12 * PFH^OF2;
MC3 = (1/A3) * W^ALPHA3 * P1^OH3_1 * P2^OH3_2 * P3^OH3_3 * P4^OH3_4 * P5^OH3_5 * P6^OH3_6 * P7^OH3_7 * P8^OH3_8 * P9^OH3_9 * P10^OH3_10 * P11^OH3_11 * P12^OH3_12 * PFH^OF3;
MC4 = (1/A4) * W^ALPHA4 * P1^OH4_1 * P2^OH4_2 * P3^OH4_3 * P4^OH4_4 * P5^OH4_5 * P6^OH4_6 * P7^OH4_7 * P8^OH4_8 * P9^OH4_9 * P10^OH4_10 * P11^OH4_11 * P12^OH4_12 * PFH^OF4;
MC5 = (1/A5) * W^ALPHA5 * P1^OH5_1 * P2^OH5_2 * P3^OH5_3 * P4^OH5_4 * P5^OH5_5 * P6^OH5_6 * P7^OH5_7 * P8^OH5_8 * P9^OH5_9 * P10^OH5_10 * P11^OH5_11 * P12^OH5_12 * PFH^OF5;
MC6 = (1/A6) * W^ALPHA6 * P1^OH6_1 * P2^OH6_2 * P3^OH6_3 * P4^OH6_4 * P5^OH6_5 * P6^OH6_6 * P7^OH6_7 * P8^OH6_8 * P9^OH6_9 * P10^OH6_10 * P11^OH6_11 * P12^OH6_12 * PFH^OF6;
MC7 = (1/A7) * W^ALPHA7 * P1^OH7_1 * P2^OH7_2 * P3^OH7_3 * P4^OH7_4 * P5^OH7_5 * P6^OH7_6 * P7^OH7_7 * P8^OH7_8 * P9^OH7_9 * P10^OH7_10 * P11^OH7_11 * P12^OH7_12 * PFH^OF7;
MC8 = (1/A8) * W^ALPHA8 * P1^OH8_1 * P2^OH8_2 * P3^OH8_3 * P4^OH8_4 * P5^OH8_5 * P6^OH8_6 * P7^OH8_7 * P8^OH8_8 * P9^OH8_9 * P10^OH8_10 * P11^OH8_11 * P12^OH8_12 * PFH^OF8;
MC9 = (1/A9) * W^ALPHA9 * P1^OH9_1 * P2^OH9_2 * P3^OH9_3 * P4^OH9_4 * P5^OH9_5 * P6^OH9_6 * P7^OH9_7 * P8^OH9_8 * P9^OH9_9 * P10^OH9_10 * P11^OH9_11 * P12^OH9_12 * PFH^OF9;
MC10 = (1/A10) * W^ALPHA10 * P1^OH10_1 * P2^OH10_2 * P3^OH10_3 * P4^OH10_4 * P5^OH10_5 * P6^OH10_6 * P7^OH10_7 * P8^OH10_8 * P9^OH10_9 * P10^OH10_10 * P11^OH10_11 * P12^OH10_12 * PFH^OF10;
MC11 = (1/A11) * W^ALPHA11 * P1^OH11_1 * P2^OH11_2 * P3^OH11_3 * P4^OH11_4 * P5^OH11_5 * P6^OH11_6 * P7^OH11_7 * P8^OH11_8 * P9^OH11_9 * P10^OH11_10 * P11^OH11_11 * P12^OH11_12 * PFH^OF11;
MC12 = (1/A12) * W^ALPHA12 * P1^OH12_1 * P2^OH12_2 * P3^OH12_3 * P4^OH12_4 * P5^OH12_5 * P6^OH12_6 * P7^OH12_7 * P8^OH12_8 * P9^OH12_9 * P10^OH12_10 * P11^OH12_11 * P12^OH12_12 * PFH^OF12;
//------------------------------------------------------------
// [2] Recursive Calvo pricing (exact nonlinear recursion), per sector
//------------------------------------------------------------
X1_1 = (MC1/P1)*Y1 + (1-DELTA1)*BETA*(C(+1)/C)^(-GAMMA)*PI1(+1)^EPS *X1_1(+1);
X2_1 = Y1 + (1-DELTA1)*BETA*(C(+1)/C)^(-GAMMA)*PI1(+1)^(EPS-1) *X2_1(+1);
PSTAR1 = (EPS/(EPS-1)) * X1_1/X2_1;
1 = (1-DELTA1)*PI1^(EPS-1) + DELTA1*PSTAR1^(1-EPS);
P1 = PI1*P1(-1);
X1_2 = (MC2/P2)*Y2 + (1-DELTA2)*BETA*(C(+1)/C)^(-GAMMA)*PI2(+1)^EPS *X1_2(+1);
X2_2 = Y2 + (1-DELTA2)*BETA*(C(+1)/C)^(-GAMMA)*PI2(+1)^(EPS-1) *X2_2(+1);
PSTAR2 = (EPS/(EPS-1)) * X1_2/X2_2;
1 = (1-DELTA2)*PI2^(EPS-1) + DELTA2*PSTAR2^(1-EPS);
P2 = PI2*P2(-1);
X1_3 = (MC3/P3)*Y3 + (1-DELTA3)*BETA*(C(+1)/C)^(-GAMMA)*PI3(+1)^EPS *X1_3(+1);
X2_3 = Y3 + (1-DELTA3)*BETA*(C(+1)/C)^(-GAMMA)*PI3(+1)^(EPS-1) *X2_3(+1);
PSTAR3 = (EPS/(EPS-1)) * X1_3/X2_3;
1 = (1-DELTA3)*PI3^(EPS-1) + DELTA3*PSTAR3^(1-EPS);
P3 = PI3*P3(-1);
X1_4 = (MC4/P4)*Y4 + (1-DELTA4)*BETA*(C(+1)/C)^(-GAMMA)*PI4(+1)^EPS *X1_4(+1);
X2_4 = Y4 + (1-DELTA4)*BETA*(C(+1)/C)^(-GAMMA)*PI4(+1)^(EPS-1) *X2_4(+1);
PSTAR4 = (EPS/(EPS-1)) * X1_4/X2_4;
1 = (1-DELTA4)*PI4^(EPS-1) + DELTA4*PSTAR4^(1-EPS);
P4 = PI4*P4(-1);
X1_5 = (MC5/P5)*Y5 + (1-DELTA5)*BETA*(C(+1)/C)^(-GAMMA)*PI5(+1)^EPS *X1_5(+1);
X2_5 = Y5 + (1-DELTA5)*BETA*(C(+1)/C)^(-GAMMA)*PI5(+1)^(EPS-1) *X2_5(+1);
PSTAR5 = (EPS/(EPS-1)) * X1_5/X2_5;
1 = (1-DELTA5)*PI5^(EPS-1) + DELTA5*PSTAR5^(1-EPS);
P5 = PI5*P5(-1);
X1_6 = (MC6/P6)*Y6 + (1-DELTA6)*BETA*(C(+1)/C)^(-GAMMA)*PI6(+1)^EPS *X1_6(+1);
X2_6 = Y6 + (1-DELTA6)*BETA*(C(+1)/C)^(-GAMMA)*PI6(+1)^(EPS-1) *X2_6(+1);
PSTAR6 = (EPS/(EPS-1)) * X1_6/X2_6;
1 = (1-DELTA6)*PI6^(EPS-1) + DELTA6*PSTAR6^(1-EPS);
P6 = PI6*P6(-1);
X1_7 = (MC7/P7)*Y7 + (1-DELTA7)*BETA*(C(+1)/C)^(-GAMMA)*PI7(+1)^EPS *X1_7(+1);
X2_7 = Y7 + (1-DELTA7)*BETA*(C(+1)/C)^(-GAMMA)*PI7(+1)^(EPS-1) *X2_7(+1);
PSTAR7 = (EPS/(EPS-1)) * X1_7/X2_7;
1 = (1-DELTA7)*PI7^(EPS-1) + DELTA7*PSTAR7^(1-EPS);
P7 = PI7*P7(-1);
X1_8 = (MC8/P8)*Y8 + (1-DELTA8)*BETA*(C(+1)/C)^(-GAMMA)*PI8(+1)^EPS *X1_8(+1);
X2_8 = Y8 + (1-DELTA8)*BETA*(C(+1)/C)^(-GAMMA)*PI8(+1)^(EPS-1) *X2_8(+1);
PSTAR8 = (EPS/(EPS-1)) * X1_8/X2_8;
1 = (1-DELTA8)*PI8^(EPS-1) + DELTA8*PSTAR8^(1-EPS);
P8 = PI8*P8(-1);
X1_9 = (MC9/P9)*Y9 + (1-DELTA9)*BETA*(C(+1)/C)^(-GAMMA)*PI9(+1)^EPS *X1_9(+1);
X2_9 = Y9 + (1-DELTA9)*BETA*(C(+1)/C)^(-GAMMA)*PI9(+1)^(EPS-1) *X2_9(+1);
PSTAR9 = (EPS/(EPS-1)) * X1_9/X2_9;
1 = (1-DELTA9)*PI9^(EPS-1) + DELTA9*PSTAR9^(1-EPS);
P9 = PI9*P9(-1);
X1_10 = (MC10/P10)*Y10 + (1-DELTA10)*BETA*(C(+1)/C)^(-GAMMA)*PI10(+1)^EPS *X1_10(+1);
X2_10 = Y10 + (1-DELTA10)*BETA*(C(+1)/C)^(-GAMMA)*PI10(+1)^(EPS-1) *X2_10(+1);
PSTAR10 = (EPS/(EPS-1)) * X1_10/X2_10;
1 = (1-DELTA10)*PI10^(EPS-1) + DELTA10*PSTAR10^(1-EPS);
P10 = PI10*P10(-1);
X1_11 = (MC11/P11)*Y11 + (1-DELTA11)*BETA*(C(+1)/C)^(-GAMMA)*PI11(+1)^EPS *X1_11(+1);
X2_11 = Y11 + (1-DELTA11)*BETA*(C(+1)/C)^(-GAMMA)*PI11(+1)^(EPS-1) *X2_11(+1);
PSTAR11 = (EPS/(EPS-1)) * X1_11/X2_11;
1 = (1-DELTA11)*PI11^(EPS-1) + DELTA11*PSTAR11^(1-EPS);
P11 = PI11*P11(-1);
X1_12 = (MC12/P12)*Y12 + (1-DELTA12)*BETA*(C(+1)/C)^(-GAMMA)*PI12(+1)^EPS *X1_12(+1);
X2_12 = Y12 + (1-DELTA12)*BETA*(C(+1)/C)^(-GAMMA)*PI12(+1)^(EPS-1) *X2_12(+1);
PSTAR12 = (EPS/(EPS-1)) * X1_12/X2_12;
1 = (1-DELTA12)*PI12^(EPS-1) + DELTA12*PSTAR12^(1-EPS);
P12 = PI12*P12(-1);
//------------------------------------------------------------
// [3] Labour demand (Cobb-Douglas cost share ALPHA_i of total cost)
//------------------------------------------------------------
L1 = ALPHA1*MC1*Y1/W;
L2 = ALPHA2*MC2*Y2/W;
L3 = ALPHA3*MC3*Y3/W;
L4 = ALPHA4*MC4*Y4/W;
L5 = ALPHA5*MC5*Y5/W;
L6 = ALPHA6*MC6*Y6/W;
L7 = ALPHA7*MC7*Y7/W;
L8 = ALPHA8*MC8*Y8/W;
L9 = ALPHA9*MC9*Y9/W;
L10 = ALPHA10*MC10*Y10/W;
L11 = ALPHA11*MC11*Y11/W;
L12 = ALPHA12*MC12*Y12/W;
Ltot = L1 + L2 + L3 + L4 + L5 + L6 + L7 + L8 + L9 + L10 + L11 + L12;
//------------------------------------------------------------
// [4] Goods market clearing: domestic consumption + dense domestic
//     intermediate demand (from ALL buying sectors) + exports
//------------------------------------------------------------
Y1 = BH1*PH*CH/P1 + (OH1_1*MC1*Y1 + OH2_1*MC2*Y2 + OH3_1*MC3*Y3 + OH4_1*MC4*Y4 + OH5_1*MC5*Y5 + OH6_1*MC6*Y6 + OH7_1*MC7*Y7 + OH8_1*MC8*Y8 + OH9_1*MC9*Y9 + OH10_1*MC10*Y10 + OH11_1*MC11*Y11 + OH12_1*MC12*Y12)/P1 + BH1*PH*EX/P1;
Y2 = BH2*PH*CH/P2 + (OH1_2*MC1*Y1 + OH2_2*MC2*Y2 + OH3_2*MC3*Y3 + OH4_2*MC4*Y4 + OH5_2*MC5*Y5 + OH6_2*MC6*Y6 + OH7_2*MC7*Y7 + OH8_2*MC8*Y8 + OH9_2*MC9*Y9 + OH10_2*MC10*Y10 + OH11_2*MC11*Y11 + OH12_2*MC12*Y12)/P2 + BH2*PH*EX/P2;
Y3 = BH3*PH*CH/P3 + (OH1_3*MC1*Y1 + OH2_3*MC2*Y2 + OH3_3*MC3*Y3 + OH4_3*MC4*Y4 + OH5_3*MC5*Y5 + OH6_3*MC6*Y6 + OH7_3*MC7*Y7 + OH8_3*MC8*Y8 + OH9_3*MC9*Y9 + OH10_3*MC10*Y10 + OH11_3*MC11*Y11 + OH12_3*MC12*Y12)/P3 + BH3*PH*EX/P3;
Y4 = BH4*PH*CH/P4 + (OH1_4*MC1*Y1 + OH2_4*MC2*Y2 + OH3_4*MC3*Y3 + OH4_4*MC4*Y4 + OH5_4*MC5*Y5 + OH6_4*MC6*Y6 + OH7_4*MC7*Y7 + OH8_4*MC8*Y8 + OH9_4*MC9*Y9 + OH10_4*MC10*Y10 + OH11_4*MC11*Y11 + OH12_4*MC12*Y12)/P4 + BH4*PH*EX/P4;
Y5 = BH5*PH*CH/P5 + (OH1_5*MC1*Y1 + OH2_5*MC2*Y2 + OH3_5*MC3*Y3 + OH4_5*MC4*Y4 + OH5_5*MC5*Y5 + OH6_5*MC6*Y6 + OH7_5*MC7*Y7 + OH8_5*MC8*Y8 + OH9_5*MC9*Y9 + OH10_5*MC10*Y10 + OH11_5*MC11*Y11 + OH12_5*MC12*Y12)/P5 + BH5*PH*EX/P5;
Y6 = BH6*PH*CH/P6 + (OH1_6*MC1*Y1 + OH2_6*MC2*Y2 + OH3_6*MC3*Y3 + OH4_6*MC4*Y4 + OH5_6*MC5*Y5 + OH6_6*MC6*Y6 + OH7_6*MC7*Y7 + OH8_6*MC8*Y8 + OH9_6*MC9*Y9 + OH10_6*MC10*Y10 + OH11_6*MC11*Y11 + OH12_6*MC12*Y12)/P6 + BH6*PH*EX/P6;
Y7 = BH7*PH*CH/P7 + (OH1_7*MC1*Y1 + OH2_7*MC2*Y2 + OH3_7*MC3*Y3 + OH4_7*MC4*Y4 + OH5_7*MC5*Y5 + OH6_7*MC6*Y6 + OH7_7*MC7*Y7 + OH8_7*MC8*Y8 + OH9_7*MC9*Y9 + OH10_7*MC10*Y10 + OH11_7*MC11*Y11 + OH12_7*MC12*Y12)/P7 + BH7*PH*EX/P7;
Y8 = BH8*PH*CH/P8 + (OH1_8*MC1*Y1 + OH2_8*MC2*Y2 + OH3_8*MC3*Y3 + OH4_8*MC4*Y4 + OH5_8*MC5*Y5 + OH6_8*MC6*Y6 + OH7_8*MC7*Y7 + OH8_8*MC8*Y8 + OH9_8*MC9*Y9 + OH10_8*MC10*Y10 + OH11_8*MC11*Y11 + OH12_8*MC12*Y12)/P8 + BH8*PH*EX/P8;
Y9 = BH9*PH*CH/P9 + (OH1_9*MC1*Y1 + OH2_9*MC2*Y2 + OH3_9*MC3*Y3 + OH4_9*MC4*Y4 + OH5_9*MC5*Y5 + OH6_9*MC6*Y6 + OH7_9*MC7*Y7 + OH8_9*MC8*Y8 + OH9_9*MC9*Y9 + OH10_9*MC10*Y10 + OH11_9*MC11*Y11 + OH12_9*MC12*Y12)/P9 + BH9*PH*EX/P9;
Y10 = BH10*PH*CH/P10 + (OH1_10*MC1*Y1 + OH2_10*MC2*Y2 + OH3_10*MC3*Y3 + OH4_10*MC4*Y4 + OH5_10*MC5*Y5 + OH6_10*MC6*Y6 + OH7_10*MC7*Y7 + OH8_10*MC8*Y8 + OH9_10*MC9*Y9 + OH10_10*MC10*Y10 + OH11_10*MC11*Y11 + OH12_10*MC12*Y12)/P10 + BH10*PH*EX/P10;
Y11 = BH11*PH*CH/P11 + (OH1_11*MC1*Y1 + OH2_11*MC2*Y2 + OH3_11*MC3*Y3 + OH4_11*MC4*Y4 + OH5_11*MC5*Y5 + OH6_11*MC6*Y6 + OH7_11*MC7*Y7 + OH8_11*MC8*Y8 + OH9_11*MC9*Y9 + OH10_11*MC10*Y10 + OH11_11*MC11*Y11 + OH12_11*MC12*Y12)/P11 + BH11*PH*EX/P11;
Y12 = BH12*PH*CH/P12 + (OH1_12*MC1*Y1 + OH2_12*MC2*Y2 + OH3_12*MC3*Y3 + OH4_12*MC4*Y4 + OH5_12*MC5*Y5 + OH6_12*MC6*Y6 + OH7_12*MC7*Y7 + OH8_12*MC8*Y8 + OH9_12*MC9*Y9 + OH10_12*MC10*Y10 + OH11_12*MC11*Y11 + OH12_12*MC12*Y12)/P12 + BH12*PH*EX/P12;
//------------------------------------------------------------
// [5] Consumption aggregation: Cobb-Douglas domestic bundle,
//     CES nest between domestic (H) and imported (F) bundles
//------------------------------------------------------------
PH = P1^BH1 * P2^BH2 * P3^BH3 * P4^BH4 * P5^BH5 * P6^BH6 * P7^BH7 * P8^BH8 * P9^BH9 * P10^BH10 * P11^BH11 * P12^BH12;
PC = ( OMEGA*PH^(1-ETA) + (1-OMEGA)*PFH^(1-ETA) )^(1/(1-ETA));
CH = OMEGA*(PH/PC)^(-ETA)*C;
CF = (1-OMEGA)*(PFH/PC)^(-ETA)*C;
PIC = PC/PC(-1);
//------------------------------------------------------------
// [6] Household Euler equation and labour supply (nonlinear CRRA/Frisch)
//------------------------------------------------------------
C^(-GAMMA) = BETA*I*(C(+1)^(-GAMMA))/PIC(+1);
W/PC = C^GAMMA * Ltot^VARPHI;
//------------------------------------------------------------
// [7] Exchange rate block: LOP for imports, UIP with debt-elastic premium
//------------------------------------------------------------
PFH = S*PF;
I = ISTAR*(1 - PSI*(BSTAR - BSTARBAR)) * RP * S(+1)/S;
//------------------------------------------------------------
// [8] Net foreign assets: current-account identity
//------------------------------------------------------------
BSTAR = (I(-1)/PIC)*BSTAR(-1) + (PH*EX - PFH*IM)/PC;
//------------------------------------------------------------
// [9] Export demand and total import demand
//------------------------------------------------------------
EX = KAPEX_SCALE*DSTAR*PX*(PH/PFH)^(-THETA_S);
IM = CF + OF1*MC1*Y1/PFH + OF2*MC2*Y2/PFH + OF3*MC3*Y3/PFH + OF4*MC4*Y4/PFH + OF5*MC5*Y5/PFH + OF6*MC6*Y6/PFH + OF7*MC7*Y7/PFH + OF8*MC8*Y8/PFH + OF9*MC9*Y9/PFH + OF10*MC10*Y10/PFH + OF11*MC11*Y11/PFH + OF12*MC12*Y12/PFH;
//------------------------------------------------------------
// [10] Policy rule (regime-dependent)
//------------------------------------------------------------
@#if REGIME == "float"
log(I/ISTAR) = PHI_PI*piDC + PHI_Y*y_gap;
@#elseif REGIME == "peg"
S = 1;
@#elseif REGIME == "managed"
log(I/ISTAR) = PHI_PI*piDC + PHI_Y*y_gap + PHI_S*log(S);
@#elseif REGIME == "cpi_it"
log(I/ISTAR) = PHI_PI*log(PIC) + PHI_Y*y_gap;
@#elseif REGIME == "ppi_it"
log(I/ISTAR) = PHI_PI*log(PH/PH(-1)) + PHI_Y*y_gap;
@#endif
//------------------------------------------------------------
// [11] DC inflation index and output gap
//------------------------------------------------------------
piDC = WDC1*log(PI1) + WDC2*log(PI2) + WDC3*log(PI3) + WDC4*log(PI4) + WDC5*log(PI5) + WDC6*log(PI6) + WDC7*log(PI7) + WDC8*log(PI8) + WDC9*log(PI9) + WDC10*log(PI10) + WDC11*log(PI11) + WDC12*log(PI12);
y_gap1 = LAMBDA_D1*(log(Y1/STEADY_STATE(Y1)) - log(A1));
y_gap2 = LAMBDA_D2*(log(Y2/STEADY_STATE(Y2)) - log(A2));
y_gap3 = LAMBDA_D3*(log(Y3/STEADY_STATE(Y3)) - log(A3));
y_gap4 = LAMBDA_D4*(log(Y4/STEADY_STATE(Y4)) - log(A4));
y_gap5 = LAMBDA_D5*(log(Y5/STEADY_STATE(Y5)) - log(A5));
y_gap6 = LAMBDA_D6*(log(Y6/STEADY_STATE(Y6)) - log(A6));
y_gap7 = LAMBDA_D7*(log(Y7/STEADY_STATE(Y7)) - log(A7));
y_gap8 = LAMBDA_D8*(log(Y8/STEADY_STATE(Y8)) - log(A8));
y_gap9 = LAMBDA_D9*(log(Y9/STEADY_STATE(Y9)) - log(A9));
y_gap10 = LAMBDA_D10*(log(Y10/STEADY_STATE(Y10)) - log(A10));
y_gap11 = LAMBDA_D11*(log(Y11/STEADY_STATE(Y11)) - log(A11));
y_gap12 = LAMBDA_D12*(log(Y12/STEADY_STATE(Y12)) - log(A12));
y_gap = y_gap1 + y_gap2 + y_gap3 + y_gap4 + y_gap5 + y_gap6 + y_gap7 + y_gap8 + y_gap9 + y_gap10 + y_gap11 + y_gap12;
//------------------------------------------------------------
// [12] Exogenous shock processes (AR(1) in logs)
//------------------------------------------------------------
log(A1) = RHO_A *log(A1(-1))  + eps_a1;
log(A2) = RHO_A *log(A2(-1))  + eps_a2;
log(A3) = RHO_A *log(A3(-1))  + eps_a3;
log(A4) = RHO_A *log(A4(-1))  + eps_a4;
log(A5) = RHO_A *log(A5(-1))  + eps_a5;
log(A6) = RHO_A *log(A6(-1))  + eps_a6;
log(A7) = RHO_A *log(A7(-1))  + eps_a7;
log(A8) = RHO_A *log(A8(-1))  + eps_a8;
log(A9) = RHO_A *log(A9(-1))  + eps_a9;
log(A10) = RHO_A *log(A10(-1))  + eps_a10;
log(A11) = RHO_A *log(A11(-1))  + eps_a11;
log(A12) = RHO_A *log(A12(-1))  + eps_a12;
log(PF) = RHO_PF*log(PF(-1))  + eps_pF;
log(DSTAR) = RHO_D*log(DSTAR(-1)) + eps_D;
log(PX) = RHO_PX*log(PX(-1)) + eps_pX;
log(RP) = RHO_RP*log(RP(-1)) + eps_rp;
//------------------------------------------------------------
// [13] Reporting: nominal GDP = absorption + net exports
//------------------------------------------------------------
GDP = PC*C + PH*EX - PFH*IM;

end;

// -------------------------------------------------------------------------
// STEADY STATE
// -------------------------------------------------------------------------
steady_state_model;
  A1 = 1; A2 = 1; A3 = 1; A4 = 1; A5 = 1; A6 = 1; A7 = 1; A8 = 1; A9 = 1; A10 = 1; A11 = 1; A12 = 1;
  PF = 1; DSTAR = 1; PX = 1; RP = 1; S = 1;
  PFH = S*PF;
  MU = EPS/(EPS-1);
  [W,C,EX,PH,PC,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,MC1,MC2,MC3,MC4,MC5,MC6,MC7,MC8,MC9,MC10,MC11,MC12,Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10,Y11,Y12,L1,L2,L3,L4,L5,L6,L7,L8,L9,L10,L11,L12,Ltot,CH,CF] = soe_ss_solve_dense_N(12,OH1_1,OH1_2,OH1_3,OH1_4,OH1_5,OH1_6,OH1_7,OH1_8,OH1_9,OH1_10,OH1_11,OH1_12,OH2_1,OH2_2,OH2_3,OH2_4,OH2_5,OH2_6,OH2_7,OH2_8,OH2_9,OH2_10,OH2_11,OH2_12,OH3_1,OH3_2,OH3_3,OH3_4,OH3_5,OH3_6,OH3_7,OH3_8,OH3_9,OH3_10,OH3_11,OH3_12,OH4_1,OH4_2,OH4_3,OH4_4,OH4_5,OH4_6,OH4_7,OH4_8,OH4_9,OH4_10,OH4_11,OH4_12,OH5_1,OH5_2,OH5_3,OH5_4,OH5_5,OH5_6,OH5_7,OH5_8,OH5_9,OH5_10,OH5_11,OH5_12,OH6_1,OH6_2,OH6_3,OH6_4,OH6_5,OH6_6,OH6_7,OH6_8,OH6_9,OH6_10,OH6_11,OH6_12,OH7_1,OH7_2,OH7_3,OH7_4,OH7_5,OH7_6,OH7_7,OH7_8,OH7_9,OH7_10,OH7_11,OH7_12,OH8_1,OH8_2,OH8_3,OH8_4,OH8_5,OH8_6,OH8_7,OH8_8,OH8_9,OH8_10,OH8_11,OH8_12,OH9_1,OH9_2,OH9_3,OH9_4,OH9_5,OH9_6,OH9_7,OH9_8,OH9_9,OH9_10,OH9_11,OH9_12,OH10_1,OH10_2,OH10_3,OH10_4,OH10_5,OH10_6,OH10_7,OH10_8,OH10_9,OH10_10,OH10_11,OH10_12,OH11_1,OH11_2,OH11_3,OH11_4,OH11_5,OH11_6,OH11_7,OH11_8,OH11_9,OH11_10,OH11_11,OH11_12,OH12_1,OH12_2,OH12_3,OH12_4,OH12_5,OH12_6,OH12_7,OH12_8,OH12_9,OH12_10,OH12_11,OH12_12,ALPHA1,ALPHA2,ALPHA3,ALPHA4,ALPHA5,ALPHA6,ALPHA7,ALPHA8,ALPHA9,ALPHA10,ALPHA11,ALPHA12,OF1,OF2,OF3,OF4,OF5,OF6,OF7,OF8,OF9,OF10,OF11,OF12,BH1,BH2,BH3,BH4,BH5,BH6,BH7,BH8,BH9,BH10,BH11,BH12,OMEGA,ETA,THETA_S,KAPEX_SCALE,GAMMA,VARPHI,MU);
  IM = PH*EX/PFH;
  PI1 = 1; PI2 = 1; PI3 = 1; PI4 = 1; PI5 = 1; PI6 = 1; PI7 = 1; PI8 = 1; PI9 = 1; PI10 = 1; PI11 = 1; PI12 = 1;
  PIC = 1;
  PSTAR1 = 1; PSTAR2 = 1; PSTAR3 = 1; PSTAR4 = 1; PSTAR5 = 1; PSTAR6 = 1; PSTAR7 = 1; PSTAR8 = 1; PSTAR9 = 1; PSTAR10 = 1; PSTAR11 = 1; PSTAR12 = 1;
  X1_1 = (MC1/P1)*Y1/(1-(1-DELTA1)*BETA); X2_1 = Y1/(1-(1-DELTA1)*BETA);
  X1_2 = (MC2/P2)*Y2/(1-(1-DELTA2)*BETA); X2_2 = Y2/(1-(1-DELTA2)*BETA);
  X1_3 = (MC3/P3)*Y3/(1-(1-DELTA3)*BETA); X2_3 = Y3/(1-(1-DELTA3)*BETA);
  X1_4 = (MC4/P4)*Y4/(1-(1-DELTA4)*BETA); X2_4 = Y4/(1-(1-DELTA4)*BETA);
  X1_5 = (MC5/P5)*Y5/(1-(1-DELTA5)*BETA); X2_5 = Y5/(1-(1-DELTA5)*BETA);
  X1_6 = (MC6/P6)*Y6/(1-(1-DELTA6)*BETA); X2_6 = Y6/(1-(1-DELTA6)*BETA);
  X1_7 = (MC7/P7)*Y7/(1-(1-DELTA7)*BETA); X2_7 = Y7/(1-(1-DELTA7)*BETA);
  X1_8 = (MC8/P8)*Y8/(1-(1-DELTA8)*BETA); X2_8 = Y8/(1-(1-DELTA8)*BETA);
  X1_9 = (MC9/P9)*Y9/(1-(1-DELTA9)*BETA); X2_9 = Y9/(1-(1-DELTA9)*BETA);
  X1_10 = (MC10/P10)*Y10/(1-(1-DELTA10)*BETA); X2_10 = Y10/(1-(1-DELTA10)*BETA);
  X1_11 = (MC11/P11)*Y11/(1-(1-DELTA11)*BETA); X2_11 = Y11/(1-(1-DELTA11)*BETA);
  X1_12 = (MC12/P12)*Y12/(1-(1-DELTA12)*BETA); X2_12 = Y12/(1-(1-DELTA12)*BETA);
  I = 1/BETA;
  BSTAR = BSTARBAR;
  piDC = 0; y_gap = 0;
  y_gap1 = 0; y_gap2 = 0; y_gap3 = 0; y_gap4 = 0; y_gap5 = 0; y_gap6 = 0; y_gap7 = 0; y_gap8 = 0; y_gap9 = 0; y_gap10 = 0; y_gap11 = 0; y_gap12 = 0;
  GDP = PC*C + PH*EX - PFH*IM;
end;

resid;
steady;
check;

// -------------------------------------------------------------------------
// SHOCKS (1 s.d. innovations)
// -------------------------------------------------------------------------
shocks;
var eps_a1  = 0.01888038^2;
var eps_a2  = 0.01888038^2;
var eps_a3  = 0.01888038^2;
var eps_a4  = 0.01888038^2;
var eps_a5  = 0.01888038^2;
var eps_a6  = 0.01888038^2;
var eps_a7  = 0.01888038^2;
var eps_a8  = 0.01888038^2;
var eps_a9  = 0.01888038^2;
var eps_a10  = 0.01888038^2;
var eps_a11  = 0.01888038^2;
var eps_a12  = 0.01888038^2;
var eps_pF  = 0.01^2;
var eps_D   = 0.01^2;
var eps_pX  = 0.01^2;
var eps_rp  = 0.01^2;
end;

// -------------------------------------------------------------------------
// SOLUTION
// -------------------------------------------------------------------------
set_dynare_seed(20260731);
stoch_simul(order=1, irf=0, periods=20000, nograph) piDC PIC y_gap I BSTAR PI1 PI2 PI3 PI4 PI5 PI6 PI7 PI8 PI9 PI10 PI11 PI12;

stoch_simul(order=1, irf=0, periods=0, nomoments, nocorr, nodecomposition, noprint, nograph) piDC PIC y_gap I BSTAR S GDP EX IM C PX RP PF DSTAR;
